---
language: node_js
node_js:
- 0.10
before_script:
  - npm install -g grunt-cli
  - git submodule update --init --recursive

env:
  global:
    - secure: bUWMJfTNJ7ip6Mm648rb77Ey4feRhrPh6DUdI8jeSnzD3Z4wCnvmvVLgVaRs2iHOnW5bv2Ml9VdcEJQpTaR1+PAMou9uOVrqAWkBKfmgvjV6m4noidtYb/bOTBgOGCgJAapps87HC4vMQlow2zT4Pg3kJE5ykfEerTL0t43oL9w=
    - secure: l/J2P6vxxinyhN0F18Lh4XnxDx3DdWIjC8BFIrB5iC56iDK8xhLlw5bA5GLUOYK8wToM3GKO9HYNLgYqK80BxDwg49XvWr7PLIB4r2x4sjeZOIQbz62Uhy4u07k3zWnH9i6XAwVhstu5KlYMSDIZsUiAT3mCaNT4RsG65/cZk1E=
    
addons:
  sauce_connect: true
